branches:
  only:
    - master
language: node_js
node_js: stable
install:
  - npm install
script:
  - ./build.sh
  - ./check.sh
deploy:
  local-dir: out
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
