language: node_js
node_js: stable
install:
  - npm install
script:
  - ./build.sh
  - node scan-github-orgs.node.js out/specs.json
after_success:
  - openssl aes-256-cbc -K $encrypted_b4940861cf48_key -iv $encrypted_b4940861cf48_iv -in deploy_key.enc -out deploy_key -d
  - chmod 0600 deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add deploy_key
  - git config --global user.email "bot@foolip.org"
  - git config --global user.name "Automat af Grönlåda"
  - ./deploy.sh
